import { AppSettings } from "../types/domain";

// --- Types & Constants ---
export const GRID_HOURS = Array.from({ length: 19 }, (_, i) => i + 6); // 06:00 to 24:00 (00:00)

export const DRINK_MENU = [
  "Coca Cola",
  "Pepsi",
  "Pivo (Beer)",
  "Voda (Water)",
  "Kava (Coffee)",
  "Monster Energy",
];

export const LOYALTY_ICONS = [
  { icon: "ph-star", color: "text-yellow-400" },
  { icon: "ph-crown", color: "text-amber-500" },
  { icon: "ph-medal", color: "text-emerald-400" },
  { icon: "ph-trophy", color: "text-cyan-400" },
  { icon: "ph-shield", color: "text-blue-500" },
  { icon: "ph-heart", color: "text-red-500" },
  { icon: "ph-fire", color: "text-orange-500" },
  { icon: "ph-lightning", color: "text-purple-400" },
  { icon: "ph-beer-stein", color: "text-amber-200" },
  { icon: "ph-target", color: "text-red-600" },
];

export const TRANSLATIONS = {
  hr: {
    title: "Train Pikado",
    subtitle: "Službena aplikacija",
    login: "Prijava",
    logout: "Odjava",
    book: "Rezerviraj",
    cancel: "Otkaži",
    cancelConfirmation: "Jeste li sigurni da želite otkazati ovaj termin?",
    yesCancel: "Da, Otkaži",
    noKeep: "Ne, Zadrži",
    free: "Slobodno",
    taken: "Zauzeto",
    yours: "Tvoje",
    selected: "Odabrano",
    closed: "Zatvoreno",
    expired: "Isteklo",
    tooFar: "Pre rano",
    cafeClosed: "Caffe Zatvoren",
    adminPanel: "Admin Postavke",
    adminLogin: "Admin Prijava",
    memberLogin: "Prijava Članova",
    weekOf: "Tjedan od",
    dayOf: "Datum",
    consecutiveDiscount: "Dnevni Popust",
    loyaltyStatus: "Status Vjernosti",
    loyaltyProgram: "Program Vjernosti",
    bookingsUntil: "rezervacija do",
    status: "statusa",
    legend: "Legenda",
    powerSession: "Power Termin",
    powerSessionActive: "Power Termin Aktivan",
    unlockText: "Rezerviraj",
    slotsInRow: "termina zaredom za",
    confirmRes: "Potvrdi Rezervaciju",
    slotsHeld: "Odabrani termini čekaju potvrdu.",
    clear: "Očisti",
    reserveNow: "Rezerviraj Sada",
    emailSent: "Potvrda poslana na email!",
    emailSentDesc: "Detalji rezervacije su poslani na",
    workingHours: "Radno Vrijeme",
    open: "Otvara",
    close: "Zatvara",
    save: "Spremi Promjene",
    enableDiscount: "Omogući Popust",
    enableLoyalty: "Omogući Program",
    rewardText: "Tekst Nagrade",
    threshold: "Prag (termina)",
    reqBookings: "Potrebno Rezervacija",
    blockedDates: "Blokirani Datumi (Zatvoreno)",
    addDate: "Dodaj Datum",
    remove: "Ukloni",
    edit: "Uredi",
    discountMonitor: "Monitor Popusta",
    qualifiedUsers: "Kvalificirani Korisnici (Ovaj Tjedan)",
    noQualified: "Nema kvalificiranih korisnika ovaj tjedan.",
    date: "Datum",
    user: "Korisnik",
    machines: "Pikado Aparati",
    addMachine: "Dodaj Aparat",
    machineName: "Ime Aparata",
    selectMachine: "Odaberi Aparat",
    history: "Povijest",
    myBookings: "Moje Rezervacije",
    noBookings: "Nemate rezervacija.",
    upcoming: "Nadolazeće",
    past: "Prošle",
    cannotBlockToday: "Nije moguće blokirati današnji dan!",
    tournaments: "Turniri",
    createTournament: "Kreiraj Turnir",
    tournamentName: "Naziv Turnira",
    format: "Format",
    single: "Pojedinačno",
    double: "Parovi",
    startTime: "Početak",
    durationHours: "Trajanje (sati)",
    participants: "Sudionici",
    register: "Prijavi se",
    withdraw: "Odustani",
    bracket: "Ždrijeb",
    startTournament: "Započni Turnir (Generiraj Ždrijeb)",
    tournamentStatusLabel: "Status",
    registrationOpen: "Prijave Otvorene",
    inProgress: "U Tijeku",
    completed: "Završeno",
    teamName: "Ime Tima / Igrača",
    winner: "Pobjednik",
    setWinner: "Odaberi Pobjednika",
    settings: "Postavke",
    delete: "Obriši",
    registeredSuccess: "Uspješno ste prijavljeni!",
    withdrawnSuccess: "Uspješno ste se odjavili.",
    users: "Korisnici",
    offers: "Ponude & Cijene",
    basePrice: "Osnovna Cijena (EUR/h)",
    createOffer: "Kreiraj Ponudu",
    offerType: "Tip Ponude",
    offerValue: "Vrijednost",
    offerTarget: "Cilj (Korisnik)",
    allUsers: "Svi Korisnici",
    sendOffer: "Pošalji Ponudu",
    offerSent: "Ponuda poslana!",
    userBlocked: "Korisnik Blokiran",
    userUnblocked: "Korisnik Odblokiran",
    block: "Blokiraj",
    unblock: "Odblokiraj",
    condition: "Uvjet",
    buyXGetY: "Rezerviraj X, Dobij Y",
    minSlots: "Min. Termina",
    rewardType: "Tip Nagrade",
    selectDrink: "Odaberi Piće",
    myOffers: "Moje Ponude",
    activeOffers: "Aktivne Ponude",
    newBadge: "Novi Status Otključan!",
    congrats: "Čestitamo",
    congratsBadge: "Dostigli ste novu razinu vjernosti!",
    addNewTier: "Dodaj Razinu",
    tierName: "Naziv Razine",
    selectOfferToApply: "Odaberi Ponudu/Kupon",
    noOffer: "Bez Kupona",
    selectTemplate: "Odaberi Predložak Ponude",
    saveTournament: "Spremi Turnir",
    addRule: "Dodaj Pravilo",
    cancelTooLate: "Prekasno za otkazivanje (manje od 2h)",
    profile: "Profil",
    editProfile: "Uredi Profil",
    fullName: "Ime i Prezime",
    email: "Email",
    avatarUrl: "Avatar URL",
    saveProfile: "Spremi Profil",
    earnedBadges: "Osvojeni Bedževi",
    activeCoupons: "Aktivni Kuponi",
    prizes: "Nagrade",
    prizePlace: "Mjesto",
    prizeDesc: "Opis Nagrade (Kupon)",
    addPrize: "Dodaj Nagradu",
    rank: "Rang",
    types: {
      discount_percent: "Popust (%)",
      fixed_price: "Fiksna Cijena",
      free_drink: "Besplatno Piće",
      free_slot: "Besplatan Termin",
    },
    days: ["Ned", "Pon", "Uto", "Sri", "Čet", "Pet", "Sub"],
    tiers: {
      rookie: "Početnik",
      regular: "Stalni Gost",
      pro: "Pikado Pro",
      legend: "Legenda",
    },
    viewMode: {
      week: "Tjedan",
      day: "Dan",
    },
    applyCoupon: "Primijeni Kupon",
    removeCoupon: "Ukloni Kupon",
    activeTournament: "Aktivni Turnir",
    viewTournament: "Pregledaj Turnir",
    totalSpend: "Ukupno Potrošeno",
    breakdown: "Detalji",
    bulkOffer: "Grupna Ponuda",
    seed: "Nositelj",
    autoSeed: "Auto Numeracija",
    recipients: "Primatelji",
    noRecipients: "Nema primatelja za ovu ponudu.",
    viewRecipients: "Pregledaj Primatelje",
    distributePrizes: "Podijeli Nagrade",
    prizesDistributed: "Nagrade Podijeljene",
  },
  en: {
    title: "Train Darts",
    subtitle: "Official App",
    login: "Log In",
    logout: "Log Out",
    book: "Book",
    cancel: "Cancel",
    cancelConfirmation: "Are you sure you want to cancel this booking?",
    yesCancel: "Yes, Cancel",
    noKeep: "No, Keep it",
    free: "Free",
    taken: "Taken",
    yours: "Yours",
    selected: "Selected",
    closed: "Closed",
    expired: "Expired",
    tooFar: "Too Early",
    cafeClosed: "Cafe Closed",
    adminPanel: "Admin Settings",
    adminLogin: "Admin Login",
    memberLogin: "Member Login",
    weekOf: "Week of",
    dayOf: "Date",
    consecutiveDiscount: "Daily Discount",
    loyaltyStatus: "Loyalty Status",
    loyaltyProgram: "Loyalty Program",
    bookingsUntil: "bookings until",
    status: "status",
    legend: "Legend",
    powerSession: "Power Session",
    powerSessionActive: "Power Session Active",
    unlockText: "Book",
    slotsInRow: "slots in a row for",
    confirmRes: "Confirm Reservation",
    slotsHeld: "Selected slots are held for booking.",
    clear: "Clear",
    reserveNow: "Reserve Now",
    emailSent: "Confirmation sent to email!",
    emailSentDesc: "Reservation details sent to",
    workingHours: "Working Hours",
    open: "Open",
    close: "Close",
    save: "Save Changes",
    enableDiscount: "Enable Discount",
    enableLoyalty: "Enable Program",
    rewardText: "Reward Text",
    threshold: "Threshold",
    reqBookings: "Bookings Required",
    blockedDates: "Blocked Dates (Closed)",
    addDate: "Add Date",
    remove: "Remove",
    edit: "Edit",
    discountMonitor: "Discount Monitor",
    qualifiedUsers: "Qualified Users (This Week)",
    noQualified: "No users qualified this week.",
    date: "Date",
    user: "User",
    machines: "Dart Machines",
    addMachine: "Add Machine",
    machineName: "Machine Name",
    selectMachine: "Select Machine",
    history: "History",
    myBookings: "My Bookings",
    noBookings: "No bookings found.",
    upcoming: "Upcoming",
    past: "Past",
    cannotBlockToday: "Cannot block the current day!",
    tournaments: "Tournaments",
    createTournament: "Create Tournament",
    tournamentName: "Tournament Name",
    format: "Format",
    single: "Single",
    double: "Double",
    startTime: "Start Time",
    durationHours: "Duration (Hours)",
    participants: "Participants",
    register: "Register",
    withdraw: "Withdraw",
    bracket: "Bracket",
    startTournament: "Start Tournament (Generate Bracket)",
    tournamentStatusLabel: "Status",
    registrationOpen: "Registration Open",
    inProgress: "In Progress",
    completed: "Completed",
    teamName: "Team / Player Name",
    winner: "Winner",
    setWinner: "Set Winner",
    settings: "Settings",
    delete: "Delete",
    registeredSuccess: "Successfully registered!",
    withdrawnSuccess: "Successfully withdrawn.",
    users: "Users",
    offers: "Offers & Pricing",
    basePrice: "Base Price (EUR/h)",
    createOffer: "Create Offer",
    offerType: "Offer Type",
    offerValue: "Value",
    offerTarget: "Target (User)",
    allUsers: "All Users",
    sendOffer: "Send Offer",
    offerSent: "Offer sent!",
    userBlocked: "User Blocked",
    userUnblocked: "User Unblocked",
    block: "Block",
    unblock: "Unblock",
    condition: "Condition",
    buyXGetY: "Book X, Get Y",
    minSlots: "Min. Slots",
    rewardType: "Reward Type",
    selectDrink: "Select Drink",
    myOffers: "My Offers",
    activeOffers: "Active Offers",
    newBadge: "New Badge Unlocked!",
    congrats: "Congratulations",
    congratsBadge: "You've reached a new loyalty tier!",
    addNewTier: "Add Tier",
    tierName: "Tier Name",
    selectOfferToApply: "Select Offer/Voucher",
    noOffer: "No Voucher",
    selectTemplate: "Select Offer Template",
    saveTournament: "Save Tournament",
    addRule: "Add Rule",
    cancelTooLate: "Too late to cancel (less than 2h)",
    profile: "Profile",
    editProfile: "Edit Profile",
    fullName: "Full Name",
    email: "Email",
    avatarUrl: "Avatar URL",
    saveProfile: "Save Profile",
    earnedBadges: "Earned Badges",
    activeCoupons: "Aktivni Kuponi",
    prizes: "Prizes",
    prizePlace: "Place",
    prizeDesc: "Prize Description (Voucher)",
    addPrize: "Add Prize",
    rank: "Rank",
    types: {
      discount_percent: "Discount (%)",
      fixed_price: "Fixed Price",
      free_drink: "Free Drink",
      free_slot: "Free Slot",
    },
    days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    tiers: {
      rookie: "Rookie",
      regular: "Regular",
      pro: "Pro",
      legend: "Legend",
    },
    viewMode: {
      week: "Week",
      day: "Day",
    },
    applyCoupon: "Apply Coupon",
    removeCoupon: "Remove Coupon",
    activeTournament: "Active Tournament",
    viewTournament: "View Tournament",
    totalSpend: "Total Spend",
    breakdown: "Breakdown",
    bulkOffer: "Bulk Offer",
    seed: "Seed",
    autoSeed: "Auto Number Seeds",
    recipients: "Recipients",
    noRecipients: "No recipients for this offer.",
    viewRecipients: "View Recipients",
    distributePrizes: "Distribute Prizes",
    prizesDistributed: "Prizes Distributed",
  },
};

export const DEFAULT_SETTINGS: AppSettings = {
  basePrice: 15,
  currency: "€",
  consecutiveDiscountTiers: [
    { threshold: 3, discount: 10 },
    { threshold: 5, discount: 20 },
  ],
  loyaltyProgram: {
    enabled: true,
    tiers: [
      {
        id: "rookie",
        name: "rookie",
        bookingsRequired: 5,
        icon: "ph-star",
        color: "text-orange-400",
        enabled: true,
      },
      {
        id: "regular",
        name: "regular",
        bookingsRequired: 10,
        icon: "ph-beer-stein",
        color: "text-blue-400",
        enabled: true,
      },
      {
        id: "pro",
        name: "pro",
        bookingsRequired: 20,
        icon: "ph-target",
        color: "text-red-500",
        enabled: true,
      },
      {
        id: "legend",
        name: "legend",
        bookingsRequired: 50,
        icon: "ph-crown",
        color: "text-yellow-400",
        enabled: true,
      },
    ],
  },
  workingHours: {
    1: { start: 6, end: 22 },
    2: { start: 6, end: 23 },
    3: { start: 6, end: 23 },
    4: { start: 6, end: 23 },
    5: { start: 6, end: 23 },
    6: { start: 8, end: 24 },
    0: { start: 15, end: 22 },
  },
  blockedDates: [],
  machines: [{ id: "dart-1", name: "Dart 1" }],
  specialOffers: [],
};